// JustFair — Product Preflight / FinePrint Schema & Enums
// Phase 11 Correction — Multi-Issuer Truth Model & Fact Authority Specification

export const EXPECTATION_PRIORITY = {
  REQUIRED: "REQUIRED",
  OPTIONAL: "OPTIONAL",
  NOT_IMPORTANT: "NOT_IMPORTANT"
};

export const MATCH_STATE = {
  MATCH: "MATCH",
  MISMATCH: "MISMATCH",
  CONDITIONAL: "CONDITIONAL",
  UNKNOWN: "UNKNOWN",
  NOT_APPLICABLE: "NOT_APPLICABLE"
};

export const PRODUCT_VERDICT = {
  MATCHES_REQUIRED_EXPECTATIONS: "MATCHES_REQUIRED_EXPECTATIONS",
  MULTIPLE_VERIFIED_MATCHES: "MULTIPLE_VERIFIED_MATCHES",
  REQUIREMENT_MISMATCH: "REQUIREMENT_MISMATCH",
  NO_VERIFIED_PRODUCT_MATCH: "NO_VERIFIED_PRODUCT_MATCH",
  UNABLE_TO_VERIFY_PRODUCT: "UNABLE_TO_VERIFY_PRODUCT"
};

export const FACT_AUTHORITY = {
  ISSUER_LEGAL_DOCS: "ISSUER_LEGAL_DOCS", // Primary-source prospectus, KID, terms
  SOLANA_ONCHAIN_RPC: "SOLANA_ONCHAIN_RPC", // Live Solana mainnet Token-2022 account state
  REGULATORY_FRAMEWORK: "REGULATORY_FRAMEWORK", // Applicable jurisdiction law (Swiss DLT, EU Prospectus, US Reg S)
  PRIMARY_API_ENDPOINT: "PRIMARY_API_ENDPOINT" // Official authenticated issuer API
};

export const FACT_EVIDENCE_STATUS = {
  VERIFIED_TRUE: "VERIFIED_TRUE",
  VERIFIED_FALSE: "VERIFIED_FALSE",
  CONDITIONAL: "CONDITIONAL",
  UNKNOWN: "UNKNOWN",
  SOURCE_CONFLICT: "SOURCE_CONFLICT"
};

export const EXPECTATION_KEYS = {
  DIRECT_SHAREHOLDER_OWNERSHIP: "DIRECT_SHAREHOLDER_OWNERSHIP",
  SHAREHOLDER_VOTING_RIGHTS: "SHAREHOLDER_VOTING_RIGHTS",
  CASH_DIVIDEND_PAYOUTS: "CASH_DIVIDEND_PAYOUTS",
  SYNTHETIC_PRICE_EXPOSURE: "SYNTHETIC_PRICE_EXPOSURE",
  SELF_CUSTODY_WALLET: "SELF_CUSTODY_WALLET",
  WALLET_TRANSFERABILITY: "WALLET_TRANSFERABILITY",
  PRIMARY_REDEMPTION_WITHOUT_KYC: "PRIMARY_REDEMPTION_WITHOUT_KYC",
  BANKRUPTCY_SEGREGATED_COLLATERAL: "BANKRUPTCY_SEGREGATED_COLLATERAL",
  TOKEN_2022_MULTIPLIER_ACCRETION: "TOKEN_2022_MULTIPLIER_ACCRETION"
};
