// JustFair — Product Preflight / FinePrint Schema & Enums
// Phase 12 — Primary-Source Product Registry & Verification Pipeline

export const EXPECTATION_PRIORITY = {
  REQUIRED: "REQUIRED",
  OPTIONAL: "OPTIONAL",
  NOT_IMPORTANT: "NOT_IMPORTANT"
};

export const MATCH_STATE = {
  MATCH: "MATCH",
  MISMATCH: "MISMATCH",
  CONDITIONAL: "CONDITIONAL",
  UNKNOWN: "UNKNOWN",
  SOURCE_CONFLICT: "SOURCE_CONFLICT",
  NOT_APPLICABLE: "NOT_APPLICABLE"
};

export const PRODUCT_VERDICT = {
  MATCHES_REQUIRED_EXPECTATIONS: "MATCHES_REQUIRED_EXPECTATIONS",
  MULTIPLE_VERIFIED_MATCHES: "MULTIPLE_VERIFIED_MATCHES",
  REQUIREMENT_MISMATCH: "REQUIREMENT_MISMATCH",
  NO_VERIFIED_PRODUCT_MATCH: "NO_VERIFIED_PRODUCT_MATCH",
  UNABLE_TO_VERIFY_PRODUCT: "UNABLE_TO_VERIFY_PRODUCT"
};

export const FACT_AUTHORITY_CLASS = {
  ISSUER_LEGAL: "ISSUER_LEGAL",                       // Prospectus, base terms, KID, legal declarations
  ISSUER_PRODUCT_DOCS: "ISSUER_PRODUCT_DOCS",         // Official product documentation, technical guides
  ISSUER_OFFICIAL_REGISTRY: "ISSUER_OFFICIAL_REGISTRY", // Official API registry, published asset lists
  SOLANA_MAINNET: "SOLANA_MAINNET",                   // Live on-chain SPL Token-2022 account state
  OFFICIAL_SOURCE_CODE: "OFFICIAL_SOURCE_CODE",       // Official issuer engineering repo (e.g. ondoprotocol/gm-solana-simulator)
  SECONDARY_DISCOVERY: "SECONDARY_DISCOVERY"          // Third-party aggregators (cannot establish VERIFIED alone)
};

export const FACT_EVIDENCE_STATUS = {
  VERIFIED_TRUE: "VERIFIED_TRUE",
  VERIFIED_FALSE: "VERIFIED_FALSE",
  CONDITIONAL: "CONDITIONAL",
  UNKNOWN: "UNKNOWN",
  SOURCE_CONFLICT: "SOURCE_CONFLICT"
};

export const VERIFICATION_STATUS = {
  VERIFIED: "VERIFIED",
  MISMATCH: "MISMATCH",
  STALE: "STALE",
  UNABLE_TO_VERIFY: "UNABLE_TO_VERIFY"
};

export const EXECUTION_SUPPORT = {
  SUPPORTED: "SUPPORTED",
  NOT_YET_SUPPORTED: "NOT_YET_SUPPORTED",
  UNAVAILABLE: "UNAVAILABLE"
};

export const VERIFICATION_REASON_CODES = {
  MINT_NOT_FOUND: "MINT_NOT_FOUND",
  TOKEN_PROGRAM_MISMATCH: "TOKEN_PROGRAM_MISMATCH",
  DECIMALS_MISMATCH: "DECIMALS_MISMATCH",
  METADATA_SYMBOL_MISMATCH: "METADATA_SYMBOL_MISMATCH",
  METADATA_NAME_MISMATCH: "METADATA_NAME_MISMATCH",
  EXPECTED_EXTENSION_MISSING: "EXPECTED_EXTENSION_MISSING",
  UNEXPECTED_EXTENSION: "UNEXPECTED_EXTENSION",
  MULTIPLIER_PARSE_FAILURE: "MULTIPLIER_PARSE_FAILURE",
  REGISTRY_SOURCE_STALE: "REGISTRY_SOURCE_STALE",
  RPC_UNAVAILABLE: "RPC_UNAVAILABLE",
  VERIFICATION_SUCCESS: "VERIFICATION_SUCCESS"
};

export const CAPABILITY_KEYS = {
  SELF_CUSTODY: "SELF_CUSTODY",
  DIRECT_SHARE_OWNERSHIP: "DIRECT_SHARE_OWNERSHIP",
  ORDINARY_VOTING_RIGHTS: "ORDINARY_VOTING_RIGHTS",
  ECONOMIC_DIVIDEND_BENEFIT: "ECONOMIC_DIVIDEND_BENEFIT",
  CASH_DIVIDEND_PAYOUT: "CASH_DIVIDEND_PAYOUT",
  WALLET_TRANSFERABILITY: "WALLET_TRANSFERABILITY",
  ONCHAIN_SECONDARY_TRADING: "ONCHAIN_SECONDARY_TRADING",
  DIRECT_ISSUER_REDEMPTION: "DIRECT_ISSUER_REDEMPTION",
  REDEMPTION_WITHOUT_KYC: "REDEMPTION_WITHOUT_KYC",
  WEEKEND_TRADING: "WEEKEND_TRADING",
  TOKEN_2022_MULTIPLIER_ACCRETION: "TOKEN_2022_MULTIPLIER_ACCRETION",
  BANKRUPTCY_SEGREGATED_COLLATERAL: "BANKRUPTCY_SEGREGATED_COLLATERAL"
};

// Aliased expectation keys for backward compatibility
export const EXPECTATION_KEYS = {
  DIRECT_SHAREHOLDER_OWNERSHIP: CAPABILITY_KEYS.DIRECT_SHARE_OWNERSHIP,
  SHAREHOLDER_VOTING_RIGHTS: CAPABILITY_KEYS.ORDINARY_VOTING_RIGHTS,
  ECONOMIC_DIVIDEND_BENEFIT: CAPABILITY_KEYS.ECONOMIC_DIVIDEND_BENEFIT,
  CASH_DIVIDEND_PAYOUTS: CAPABILITY_KEYS.CASH_DIVIDEND_PAYOUT,
  SYNTHETIC_PRICE_EXPOSURE: "SYNTHETIC_PRICE_EXPOSURE",
  SELF_CUSTODY_WALLET: CAPABILITY_KEYS.SELF_CUSTODY,
  WALLET_TRANSFERABILITY: CAPABILITY_KEYS.WALLET_TRANSFERABILITY,
  WEEKEND_OR_OFF_HOURS_TRADING: CAPABILITY_KEYS.WEEKEND_TRADING,
  PRIMARY_REDEMPTION_WITHOUT_KYC: CAPABILITY_KEYS.REDEMPTION_WITHOUT_KYC,
  BANKRUPTCY_SEGREGATED_COLLATERAL: CAPABILITY_KEYS.BANKRUPTCY_SEGREGATED_COLLATERAL,
  TOKEN_2022_MULTIPLIER_ACCRETION: CAPABILITY_KEYS.TOKEN_2022_MULTIPLIER_ACCRETION
};
