// JustFair — Product Preflight / FinePrint Schema & Enums
// Phase 12 — Primary-Source Product Registry & Verification Pipeline

export const EXPECTATION_PRIORITY = {
  REQUIRED: "REQUIRED",
  OPTIONAL: "OPTIONAL",
  NOT_IMPORTANT: "NOT_IMPORTANT"
};

export const MATCH_STATE = {
  MATCH: "MATCH",
  MISMATCH: "MISMATCH",
  CONDITIONAL: "CONDITIONAL",
  UNKNOWN: "UNKNOWN",
  SOURCE_CONFLICT: "SOURCE_CONFLICT",
  NOT_APPLICABLE: "NOT_APPLICABLE"
};

export const PREFLIGHT_MODE = {
  UNDERLYING_DISCOVERY: "UNDERLYING_DISCOVERY",
  SPECIFIC_PRODUCT_CHECK: "SPECIFIC_PRODUCT_CHECK"
};

export const PRODUCT_EVALUATION_STATE = {
  MATCH: "MATCH",
  MISMATCH: "MISMATCH",
  CONDITIONAL_MATCH: "CONDITIONAL_MATCH",
  UNABLE_TO_VERIFY: "UNABLE_TO_VERIFY"
};

export const UNDERLYING_RESULT_STATE = {
  MATCHES_REQUIRED_EXPECTATIONS: "MATCHES_REQUIRED_EXPECTATIONS",
  MULTIPLE_VERIFIED_MATCHES: "MULTIPLE_VERIFIED_MATCHES",
  CONDITIONAL_MATCHES: "CONDITIONAL_MATCHES",
  NO_VERIFIED_PRODUCT_MATCH: "NO_VERIFIED_PRODUCT_MATCH",
  UNABLE_TO_VERIFY_PRODUCT: "UNABLE_TO_VERIFY_PRODUCT"
};

// Backward-compatible alias
export const PRODUCT_VERDICT = {
  ...UNDERLYING_RESULT_STATE,
  REQUIREMENT_MISMATCH: "REQUIREMENT_MISMATCH"
};

export const CONSUMER_EXPECTATION_PROMPTS = {
  SELF_CUSTODY: {
    key: "SELF_CUSTODY",
    prompt: "I want to hold it in my own wallet.",
    shortLabel: "Self-Custodial Storage"
  },
  DIRECT_SHARE_OWNERSHIP: {
    key: "DIRECT_SHARE_OWNERSHIP",
    prompt: "I need to directly own shares of the underlying company.",
    shortLabel: "Direct Share Ownership"
  },
  ORDINARY_VOTING_RIGHTS: {
    key: "ORDINARY_VOTING_RIGHTS",
    prompt: "I need normal shareholder voting rights.",
    shortLabel: "Corporate Voting Rights"
  },
  ECONOMIC_DIVIDEND_BENEFIT: {
    key: "ECONOMIC_DIVIDEND_BENEFIT",
    prompt: "I want to benefit economically when the company pays dividends.",
    shortLabel: "Economic Dividend Benefit"
  },
  CASH_DIVIDEND_PAYOUT: {
    key: "CASH_DIVIDEND_PAYOUT",
    prompt: "I need dividends paid directly to me as cash/stablecoins.",
    shortLabel: "Cash Dividend Payouts"
  },
  WALLET_TRANSFERABILITY: {
    key: "WALLET_TRANSFERABILITY",
    prompt: "I want to move the token between my own wallets.",
    shortLabel: "Wallet Transferability"
  },
  ONCHAIN_SECONDARY_TRADING: {
    key: "ONCHAIN_SECONDARY_TRADING",
    prompt: "I want to trade it onchain.",
    shortLabel: "On-Chain Secondary Trading"
  },
  DIRECT_ISSUER_REDEMPTION: {
    key: "DIRECT_ISSUER_REDEMPTION",
    prompt: "I need the option to redeem directly with the issuer.",
    shortLabel: "Direct Primary Redemption"
  },
  REDEMPTION_WITHOUT_KYC: {
    key: "REDEMPTION_WITHOUT_KYC",
    prompt: "I need redemption without completing issuer KYC.",
    shortLabel: "Redemption Without KYC"
  },
  WEEKEND_TRADING: {
    key: "WEEKEND_TRADING",
    prompt: "I need the ability to trade on weekends.",
    shortLabel: "Weekend & Off-Hours Trading"
  }
};

export const FACT_AUTHORITY_CLASS = {
  ISSUER_LEGAL: "ISSUER_LEGAL",                       // Prospectus, base terms, KID, legal declarations
  ISSUER_PRODUCT_DOCS: "ISSUER_PRODUCT_DOCS",         // Official product documentation, technical guides
  ISSUER_OFFICIAL_REGISTRY: "ISSUER_OFFICIAL_REGISTRY", // Official API registry, published asset lists
  SOLANA_MAINNET: "SOLANA_MAINNET",                   // Live on-chain SPL Token-2022 account state
  OFFICIAL_SOURCE_CODE: "OFFICIAL_SOURCE_CODE",       // Official issuer engineering repo (e.g. ondoprotocol/gm-solana-simulator)
  SECONDARY_DISCOVERY: "SECONDARY_DISCOVERY"          // Third-party aggregators (cannot establish VERIFIED alone)
};

export const FACT_EVIDENCE_STATUS = {
  VERIFIED_TRUE: "VERIFIED_TRUE",
  VERIFIED_FALSE: "VERIFIED_FALSE",
  CONDITIONAL: "CONDITIONAL",
  UNKNOWN: "UNKNOWN",
  SOURCE_CONFLICT: "SOURCE_CONFLICT"
};

export const VERIFICATION_STATUS = {
  VERIFIED: "VERIFIED",
  MISMATCH: "MISMATCH",
  STALE: "STALE",
  UNABLE_TO_VERIFY: "UNABLE_TO_VERIFY"
};

export const EXECUTION_SUPPORT = {
  SUPPORTED: "SUPPORTED",
  NOT_YET_SUPPORTED: "NOT_YET_SUPPORTED",
  UNAVAILABLE: "UNAVAILABLE"
};

export const VERIFICATION_REASON_CODES = {
  MINT_NOT_FOUND: "MINT_NOT_FOUND",
  TOKEN_PROGRAM_MISMATCH: "TOKEN_PROGRAM_MISMATCH",
  DECIMALS_MISMATCH: "DECIMALS_MISMATCH",
  METADATA_SYMBOL_MISMATCH: "METADATA_SYMBOL_MISMATCH",
  METADATA_NAME_MISMATCH: "METADATA_NAME_MISMATCH",
  METADATA_UNAVAILABLE: "METADATA_UNAVAILABLE",
  METADATA_DECODE_FAILURE: "METADATA_DECODE_FAILURE",
  METADATA_POINTER_UNAVAILABLE: "METADATA_POINTER_UNAVAILABLE",
  EXPECTED_EXTENSION_MISSING: "EXPECTED_EXTENSION_MISSING",
  UNEXPECTED_EXTENSION: "UNEXPECTED_EXTENSION",
  MULTIPLIER_PARSE_FAILURE: "MULTIPLIER_PARSE_FAILURE",
  REGISTRY_SOURCE_STALE: "REGISTRY_SOURCE_STALE",
  RPC_UNAVAILABLE: "RPC_UNAVAILABLE",
  VERIFICATION_SUCCESS: "VERIFICATION_SUCCESS"
};

export const CAPABILITY_KEYS = {
  SELF_CUSTODY: "SELF_CUSTODY",
  DIRECT_SHARE_OWNERSHIP: "DIRECT_SHARE_OWNERSHIP",
  ORDINARY_VOTING_RIGHTS: "ORDINARY_VOTING_RIGHTS",
  ECONOMIC_DIVIDEND_BENEFIT: "ECONOMIC_DIVIDEND_BENEFIT",
  CASH_DIVIDEND_PAYOUT: "CASH_DIVIDEND_PAYOUT",
  WALLET_TRANSFERABILITY: "WALLET_TRANSFERABILITY",
  ONCHAIN_SECONDARY_TRADING: "ONCHAIN_SECONDARY_TRADING",
  DIRECT_ISSUER_REDEMPTION: "DIRECT_ISSUER_REDEMPTION",
  REDEMPTION_WITHOUT_KYC: "REDEMPTION_WITHOUT_KYC",
  WEEKEND_TRADING: "WEEKEND_TRADING",
  TOKEN_2022_MULTIPLIER_ACCRETION: "TOKEN_2022_MULTIPLIER_ACCRETION",
  COLLATERAL_PROTECTION_STRUCTURE: "COLLATERAL_PROTECTION_STRUCTURE",
  BANKRUPTCY_SEGREGATED_COLLATERAL: "COLLATERAL_PROTECTION_STRUCTURE"
};

// Aliased expectation keys for backward compatibility
export const EXPECTATION_KEYS = {
  DIRECT_SHAREHOLDER_OWNERSHIP: CAPABILITY_KEYS.DIRECT_SHARE_OWNERSHIP,
  SHAREHOLDER_VOTING_RIGHTS: CAPABILITY_KEYS.ORDINARY_VOTING_RIGHTS,
  ECONOMIC_DIVIDEND_BENEFIT: CAPABILITY_KEYS.ECONOMIC_DIVIDEND_BENEFIT,
  CASH_DIVIDEND_PAYOUTS: CAPABILITY_KEYS.CASH_DIVIDEND_PAYOUT,
  SYNTHETIC_PRICE_EXPOSURE: "SYNTHETIC_PRICE_EXPOSURE",
  SELF_CUSTODY_WALLET: CAPABILITY_KEYS.SELF_CUSTODY,
  WALLET_TRANSFERABILITY: CAPABILITY_KEYS.WALLET_TRANSFERABILITY,
  WEEKEND_OR_OFF_HOURS_TRADING: CAPABILITY_KEYS.WEEKEND_TRADING,
  PRIMARY_REDEMPTION_WITHOUT_KYC: CAPABILITY_KEYS.REDEMPTION_WITHOUT_KYC,
  COLLATERAL_PROTECTION_STRUCTURE: CAPABILITY_KEYS.COLLATERAL_PROTECTION_STRUCTURE,
  BANKRUPTCY_SEGREGATED_COLLATERAL: CAPABILITY_KEYS.COLLATERAL_PROTECTION_STRUCTURE,
  TOKEN_2022_MULTIPLIER_ACCRETION: CAPABILITY_KEYS.TOKEN_2022_MULTIPLIER_ACCRETION
};

